### ISSUE TITLE
App crashes after login when using docker image

### ISSUE THREAD

**Issue by asherbar** [asherbar/InspectorDB#19]
Traceback:
```
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR [log.py:228 -         log_response() ] Internal Server Error: /app/login/
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self.cursor.execute(sql, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return Database.Cursor.execute(self, query, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR sqlite3.OperationalError: no such table: auth_user
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR The above exception was the direct cause of the following exception:
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     response = get_response(request)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     response = self.process_exception_by_middleware(e, request)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self.dispatch(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return bound_method(*args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return view(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return bound_method(*args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     response = view_func(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return bound_method(*args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     response = view_func(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return super().dispatch(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return handler(request, *args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     if form.is_valid():
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self.is_bound and not self.errors
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     self.full_clean()
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     self._clean_form()
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     cleaned_data = self.clean()
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 196, in clean
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     self.user_cache = authenticate(self.request, username=username, password=password)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     user = backend.authenticate(request, **credentials)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/inspectorDB/app/logic/authentication/auth_backend.py", line 15, in authenticate
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     user = User.objects.get(username=username)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return getattr(self.get_queryset(), name)(*args, **kwargs)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     num = len(clone)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     self._fetch_all()
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     self._result_cache = list(self._iterable_class(self))
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     cursor.execute(sql, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return executor(sql, params, many, context)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self.cursor.execute(sql, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     raise dj_exc_value.with_traceback(traceback) from exc_value
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return self.cursor.execute(sql, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR   File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR     return Database.Cursor.execute(self, query, params)
   2019-02-28T14:59:06.82+0200 [APP/PROC/WEB/0] ERR django.db.utils.OperationalError: no such table: auth_user
```

**Comment by asherbar** [comment]
Unable to reproduce
